### ISSUE TITLE
Workshop collection: mods & assets usable as well?

### ISSUE THREAD

**Issue by PPillau** [jusito/docker-ttt#1]
Just to clarify: Can the workshop collection which I'm using with the server-container only contain maps or assets and mods as well? Are there any limitations to what mods/plugins I can use with this image?

**Comment by jusito** [comment]
No limitation.
If you are using the WORKSHOP_AUTOLOAD option (default yes) every user which is connecting is forced to load every element from the collection. No user needs to subscribe to your collection. The script just get every workshop mod id and add it with [AddWorkshop](https://wiki.facepunch.com/gmod/resource.AddWorkshop). The [script](https://github.com/jusito/docker-ttt/blob/master/gmod/forceWorkshopDownload.sh) skips linked collections but the server will not skip it.

If you have on your main collection maps with activated autoload, they are forced to download every map on every connection (ofc after the first, if you dont change add more maps the maps are already downloaded but not everyone has a fast connection). And thats why I suggest, if you want to use this autoload option, create a second collection with map and add this collection to your non-map collection.

Example: https://steamcommunity.com/workshop/filedetails/?id=1895900191
