### ISSUE TITLE
ULX command not found

### ISSUE THREAD

**Issue by pstoebenau** [jusito/docker-ttt#13]
I'm not sure if I just don't know what I'm doing, but I can't get ulx to work. I manually installed it and it still doesn't show up in the gmodserver console. I tried connecting through rcon and it still doesn't work. I can set cvars but I can't run ulx. Any help would be appreciated.

**Comment by jusito** [comment]
It should be enough if its part of the workshop collection and you also need ulib i think like here:
https://steamcommunity.com/workshop/filedetails/?id=1895900191

**Comment by pstoebenau** [comment]
Thank you for the quick reply! Adding it to the workshop collection works. I'm not sure why adding both ulx and ulib to the /home/steam/addons folder and restarting the server doesn't work.
