### ISSUE TITLE
Exiting on Startup

### ISSUE THREAD

**Issue by Caligula599** [jusito/docker-ttt#16]
Hello, somehow my Container keeps exiting after a Certain point of starting up.
I uploaded the Container`s log in here. Could you please have a look at it? Maybe I did something wrong installing the Container.
[logs.txt](https://github.com/jusito/docker-ttt/files/10774500/logs.txt)

**Comment by jusito** [comment]
Heyho, try the "-develop" version of the image.

**Comment by Caligula599** [comment]
Alright. I reinstalled it with the develop image, that issue is resolved. But now the Container just shuts down after processing the workshop collection. 
[logs 2.txt](https://github.com/jusito/docker-ttt/files/10774756/logs.2.txt)

**Comment by jusito** [comment]
Your workshop collection id is expected to be a whole number, see here:
https://github.com/jusito/docker-ttt/blob/master/gmod/forceWorkshopDownload.sh#L25-L27
So its expected that this url is working:
https://steamcommunity.com/sharedfiles/filedetails/?id=Caligula599
You can open it in steam and just copy the id from the top.

**Comment by jusito** [comment]
could also be that you just sanitized it, you could also set an environment variable for xtrace to get detailed output:
DEBUGGING=true

**Comment by Caligula599** [comment]
Alright I changed the Workshop Code. Its perfect.

**Comment by jusito** [comment]
Do you have further questions or can we close this issue?

**Comment by Caligula599** [comment]
I was able to resolve the Issue. Thanks for the support the issue can be closed.
