### ISSUE TITLE
How to add custom files to server

### ISSUE THREAD

**Issue by tzabbi** [jusito/docker-ttt#22]
Hi there,

can i just add custom files to the server via copy the files to the volume mount?
In my case there are sound files for the endofround plugin.

thanks Tom

**Comment by jusito** [comment]
Yes you can, e.g. I used ftp server for serverfiles.
Just if you have a custom script which should be invoked before/after server start, this will not work. Would need to add a hook and looks like I didn't add it here.

Edit: [Ftp examples ](https://github.com/jusito/docker-ttt#for-filezilla)

**Comment by jusito** [comment]
ah just a note, dont miss to change the owner of the file afterwards.
`docker exec -it CONTAINER chown -R 10000:10000 /home/steam `
maybe you need:
`docker exec -it -u root CONTAINER chown -R 10000:10000 /home/steam `

**Comment by tzabbi** [comment]
alright thanks i will test it and maybe add it to your README.md :)
